###################
# Gnüwhine recipe #
###################

# Make your own Gnüwhine
# Choose from the following ingredients: krambambuli, rum, cognac, sugar, cinnamon, coffee, lemon
# the key is the ingredient, the value is the amount in percentage. Example:
# rum: 70%

# Make a fork from https://github.com/hsbxl/gnuwhine and your fork will be listed on our interface.
# For making multiple variants, use branches.
#
# Happy Gnüwhining!

krambambuli: 60%
rum: 30%
lemon: 8%
sugar: 1%
cinnamon: 1%
